create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

alter table public.subscribers enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'subscribers'
      and policyname = 'allow public insert'
  ) then
    create policy "allow public insert"
      on public.subscribers
      for insert
      to anon, authenticated
      with check (true);
  end if;
end $$;
